version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: nba_postgres
    restart: unless-stopped
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: nba_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - nba_pgdata:/var/lib/postgresql/data

volumes:
  nba_pgdata:
